name: AssistantGPT Backend

on:
  pull_request:
    paths:
      - 'backend/**' # Only trigger the workflow if changes are made in the backend folder

jobs:
  CI:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version-file: './backend/.python-version'
          cache: 'pip'
          cache-dependency-path: './backend/requirements.txt'
          check-latest: true
      - name: Install dependencies
        run: |
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest
