name: Backend
on:
  #  push:
  #    branches: [ "main" ]
  #    paths:
  #      - 'platform/**'
  pull_request:
    paths:
      - 'backend/**'

jobs:
  black:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: platform
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
          cache: 'poetry'
      - run: poetry install
      - name: Run black check
        run: poetry run black --check .

  mypy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: platform
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
          cache: 'poetry'
      - run: poetry install
      - name: Run mypy check
        run: poetry run mypy .

  pytest:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
          cache: 'poetry'
      - run: poetry install
      - name: Run pytest check
        run: poetry run pytest -vv --cov="backend" .
        env:
          BACKEND_PLATFORM_HOST: "0.0.0.0"
          BACKEND_PLATFORM_DB_HOST: localhost
          BACKEND_PLATFORM_KAFKA_BOOTSTRAP_SERVERS: '["localhost:9092"]'
